version: '3.8'
services:
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes: 
      - ./postgresql:/var/lib/postgresql/data
volumes:
  db:
    driver: local